logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor: TRACE
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uni_sports_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: "${MYSQL_KEY}"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

cloudinary:
  cloud-name: dhrjhgp37
  api-key: 353485742747155
  api-secret: "${CLOUDINARY_SECRET}"